// Code generated by mockery v1.0.0. DO NOT EDIT.

package sladder

import mock "github.com/stretchr/testify/mock"

// MockEngineInstance is an autogenerated mock type for the EngineInstance type
type MockEngineInstance struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockEngineInstance) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Init provides a mock function with given fields: _a0
func (_m *MockEngineInstance) Init(_a0 *Cluster) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Cluster) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
