// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.2
// source: engine/gossip/pb/pb.proto

package pb

import (
	proto1 "github.com/crossmesh/sladder/proto"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GossipMessage_Type int32

const (
	GossipMessage_Ping    GossipMessage_Type = 0
	GossipMessage_Ack     GossipMessage_Type = 1
	GossipMessage_Sync    GossipMessage_Type = 2
	GossipMessage_PingReq GossipMessage_Type = 3
)

// Enum value maps for GossipMessage_Type.
var (
	GossipMessage_Type_name = map[int32]string{
		0: "Ping",
		1: "Ack",
		2: "Sync",
		3: "PingReq",
	}
	GossipMessage_Type_value = map[string]int32{
		"Ping":    0,
		"Ack":     1,
		"Sync":    2,
		"PingReq": 3,
	}
)

func (x GossipMessage_Type) Enum() *GossipMessage_Type {
	p := new(GossipMessage_Type)
	*p = x
	return p
}

func (x GossipMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GossipMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_gossip_pb_pb_proto_enumTypes[0].Descriptor()
}

func (GossipMessage_Type) Type() protoreflect.EnumType {
	return &file_engine_gossip_pb_pb_proto_enumTypes[0]
}

func (x GossipMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GossipMessage_Type.Descriptor instead.
func (GossipMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_engine_gossip_pb_pb_proto_rawDescGZIP(), []int{0, 0}
}

type Sync_Type int32

const (
	Sync_Unknown  Sync_Type = 0
	Sync_PushPull Sync_Type = 1
	Sync_Push     Sync_Type = 2
)

// Enum value maps for Sync_Type.
var (
	Sync_Type_name = map[int32]string{
		0: "Unknown",
		1: "PushPull",
		2: "Push",
	}
	Sync_Type_value = map[string]int32{
		"Unknown":  0,
		"PushPull": 1,
		"Push":     2,
	}
)

func (x Sync_Type) Enum() *Sync_Type {
	p := new(Sync_Type)
	*p = x
	return p
}

func (x Sync_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sync_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_gossip_pb_pb_proto_enumTypes[1].Descriptor()
}

func (Sync_Type) Type() protoreflect.EnumType {
	return &file_engine_gossip_pb_pb_proto_enumTypes[1]
}

func (x Sync_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sync_Type.Descriptor instead.
func (Sync_Type) EnumDescriptor() ([]byte, []int) {
	return file_engine_gossip_pb_pb_proto_rawDescGZIP(), []int{4, 0}
}

// GossipMessage is container of message body.
type GossipMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type GossipMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.GossipMessage_Type" json:"type,omitempty"`
	Body *any.Any           `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_gossip_pb_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_engine_gossip_pb_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_engine_gossip_pb_pb_proto_rawDescGZIP(), []int{0}
}

func (x *GossipMessage) GetType() GossipMessage_Type {
	if x != nil {
		return x.Type
	}
	return GossipMessage_Ping
}

func (x *GossipMessage) GetBody() *any.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

// Ping request.
type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_gossip_pb_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_engine_gossip_pb_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_engine_gossip_pb_pb_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Ping acknowledge
type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NamesProxyFor []string `protobuf:"bytes,2,rep,name=names_proxy_for,json=namesProxyFor,proto3" json:"names_proxy_for,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_gossip_pb_pb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_engine_gossip_pb_pb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_engine_gossip_pb_pb_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Ack) GetNamesProxyFor() []string {
	if x != nil {
		return x.NamesProxyFor
	}
	return nil
}

// PingReq request.
type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name []string `protobuf:"bytes,2,rep,name=name,proto3" json:"name,omitempty"`
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_gossip_pb_pb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_engine_gossip_pb_pb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_engine_gossip_pb_pb_proto_rawDescGZIP(), []int{3}
}

func (x *PingReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PingReq) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

// Cluster member synchronization.
type Sync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cluster *proto1.Cluster `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Type    Sync_Type       `protobuf:"varint,3,opt,name=type,proto3,enum=pb.Sync_Type" json:"type,omitempty"`
}

func (x *Sync) Reset() {
	*x = Sync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_engine_gossip_pb_pb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_engine_gossip_pb_pb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_engine_gossip_pb_pb_proto_rawDescGZIP(), []int{4}
}

func (x *Sync) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sync) GetCluster() *proto1.Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *Sync) GetType() Sync_Type {
	if x != nil {
		return x.Type
	}
	return Sync_Unknown
}

var File_engine_gossip_pb_pb_proto protoreflect.FileDescriptor

var file_engine_gossip_pb_pb_proto_rawDesc = []byte{
	0x0a, 0x19, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x2f,
	0x70, 0x62, 0x2f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a,
	0x0d, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0x30, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x50, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x53, 0x79, 0x6e, 0x63, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x10, 0x03, 0x22, 0x16, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d,
	0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x5f, 0x70,
	0x72, 0x6f, 0x78, 0x79, 0x5f, 0x66, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x46, 0x6f, 0x72, 0x22, 0x2d, 0x0a,
	0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x90, 0x01, 0x0a,
	0x04, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x21, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x2b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x50,
	0x75, 0x6c, 0x6c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x10, 0x02, 0x42,
	0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72,
	0x6f, 0x73, 0x73, 0x6d, 0x65, 0x73, 0x68, 0x2f, 0x73, 0x6c, 0x61, 0x64, 0x64, 0x65, 0x72, 0x2f,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_engine_gossip_pb_pb_proto_rawDescOnce sync.Once
	file_engine_gossip_pb_pb_proto_rawDescData = file_engine_gossip_pb_pb_proto_rawDesc
)

func file_engine_gossip_pb_pb_proto_rawDescGZIP() []byte {
	file_engine_gossip_pb_pb_proto_rawDescOnce.Do(func() {
		file_engine_gossip_pb_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_engine_gossip_pb_pb_proto_rawDescData)
	})
	return file_engine_gossip_pb_pb_proto_rawDescData
}

var file_engine_gossip_pb_pb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_engine_gossip_pb_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_engine_gossip_pb_pb_proto_goTypes = []interface{}{
	(GossipMessage_Type)(0), // 0: pb.GossipMessage.Type
	(Sync_Type)(0),          // 1: pb.Sync.Type
	(*GossipMessage)(nil),   // 2: pb.GossipMessage
	(*Ping)(nil),            // 3: pb.Ping
	(*Ack)(nil),             // 4: pb.Ack
	(*PingReq)(nil),         // 5: pb.PingReq
	(*Sync)(nil),            // 6: pb.Sync
	(*any.Any)(nil),         // 7: google.protobuf.Any
	(*proto1.Cluster)(nil),  // 8: proto.Cluster
}
var file_engine_gossip_pb_pb_proto_depIdxs = []int32{
	0, // 0: pb.GossipMessage.type:type_name -> pb.GossipMessage.Type
	7, // 1: pb.GossipMessage.body:type_name -> google.protobuf.Any
	8, // 2: pb.Sync.cluster:type_name -> proto.Cluster
	1, // 3: pb.Sync.type:type_name -> pb.Sync.Type
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_engine_gossip_pb_pb_proto_init() }
func file_engine_gossip_pb_pb_proto_init() {
	if File_engine_gossip_pb_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_engine_gossip_pb_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_gossip_pb_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_gossip_pb_pb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_gossip_pb_pb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_engine_gossip_pb_pb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_engine_gossip_pb_pb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_gossip_pb_pb_proto_goTypes,
		DependencyIndexes: file_engine_gossip_pb_pb_proto_depIdxs,
		EnumInfos:         file_engine_gossip_pb_pb_proto_enumTypes,
		MessageInfos:      file_engine_gossip_pb_pb_proto_msgTypes,
	}.Build()
	File_engine_gossip_pb_pb_proto = out.File
	file_engine_gossip_pb_pb_proto_rawDesc = nil
	file_engine_gossip_pb_pb_proto_goTypes = nil
	file_engine_gossip_pb_pb_proto_depIdxs = nil
}
